name: zengen_generator
version: 0.4.1
author: Alexandre Ardhuin <alexandre.ardhuin@gmail.com>
description: A package to generate boilerplate code.
homepage: https://github.com/a14n/zengen
environment:
  sdk: '>=1.12.0 <2.0.0'
dependencies:
  source_gen: ^0.5.0
  zengen: 0.4.1
dev_dependencies:
  browser: ^0.10.0
  test: ^0.12.0
dependency_overrides:
  zengen:
    path: ../main_lib