name: zengen
description: A transformer to generate boilerplate code.
version: 0.1.1-dev
author: Alexandre Ardhuin <alexandre.ardhuin@gmail.com>
homepage: https://github.com/a14n/zengen
dependencies:
  analyzer: '>=0.15.3 <0.16.0'
  barback: '>=0.12.0 <0.13.0'
  quiver: '>=0.18.2 <0.19.0'
dev_dependencies:
  unittest: '>=0.10.0 <0.11.0'
  path: '>=1.1.0 <2.0.0'
transformers:
- zengen
