name: zengen
version: 0.2.8
author: Alexandre Ardhuin <alexandre.ardhuin@gmail.com>
description: A transformer to generate boilerplate code.
homepage: https://github.com/a14n/zengen
dependencies:
  barback: '>=0.13.0 <0.14.0'
  code_transformers: '>=0.1.4+1 <0.2.0'
  collection: '>=0.9.3+1 <0.10.0'
  quiver: '>=0.18.2 <0.20.0'
dev_dependencies:
  path: '>=1.1.0 <2.0.0'
  unittest: '>=0.10.0 <0.11.0'
