name: zengen
version: 0.3.0-dev
author: Alexandre Ardhuin <alexandre.ardhuin@gmail.com>
description: A package to generate boilerplate code.
homepage: https://github.com/a14n/zengen
environment:
  sdk: '>=1.10.0 <2.0.0'
dependencies:
  source_gen: ^0.4.0
  quiver: '>=0.18.2 <0.20.0'
dev_dependencies:
  browser: ^0.10.0
  test: ^0.12.0
